/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddAssetsDto {
    #[serde(rename = "assetIds")]
    pub asset_ids: Vec<String>,
}

impl AddAssetsDto {
    pub fn new(asset_ids: Vec<String>) -> AddAssetsDto {
        AddAssetsDto {
            asset_ids,
        }
    }
}


