/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddUsersDto {
    #[serde(rename = "sharedUserIds")]
    pub shared_user_ids: Vec<String>,
}

impl AddUsersDto {
    pub fn new(shared_user_ids: Vec<String>) -> AddUsersDto {
        AddUsersDto {
            shared_user_ids,
        }
    }
}


