/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminSignupResponseDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "firstName")]
    pub first_name: String,
    #[serde(rename = "lastName")]
    pub last_name: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl AdminSignupResponseDto {
    pub fn new(id: String, email: String, first_name: String, last_name: String, created_at: String) -> AdminSignupResponseDto {
        AdminSignupResponseDto {
            id,
            email,
            first_name,
            last_name,
            created_at,
        }
    }
}


