/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AlbumCountResponseDto {
    #[serde(rename = "owned")]
    pub owned: i32,
    #[serde(rename = "shared")]
    pub shared: i32,
    #[serde(rename = "sharing")]
    pub sharing: i32,
}

impl AlbumCountResponseDto {
    pub fn new(owned: i32, shared: i32, sharing: i32) -> AlbumCountResponseDto {
        AlbumCountResponseDto {
            owned,
            shared,
            sharing,
        }
    }
}


