/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetCountByTimeBucketResponseDto {
    #[serde(rename = "totalCount")]
    pub total_count: i32,
    #[serde(rename = "buckets")]
    pub buckets: Vec<crate::models::AssetCountByTimeBucket>,
}

impl AssetCountByTimeBucketResponseDto {
    pub fn new(total_count: i32, buckets: Vec<crate::models::AssetCountByTimeBucket>) -> AssetCountByTimeBucketResponseDto {
        AssetCountByTimeBucketResponseDto {
            total_count,
            buckets,
        }
    }
}


