/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetFileUploadResponseDto {
    #[serde(rename = "id")]
    pub id: String,
}

impl AssetFileUploadResponseDto {
    pub fn new(id: String) -> AssetFileUploadResponseDto {
        AssetFileUploadResponseDto {
            id,
        }
    }
}


