/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetTypeEnum {
    #[serde(rename = "IMAGE")]
    Image,
    #[serde(rename = "VIDEO")]
    Video,
    #[serde(rename = "AUDIO")]
    Audio,
    #[serde(rename = "OTHER")]
    Other,

}

impl ToString for AssetTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Image => String::from("IMAGE"),
            Self::Video => String::from("VIDEO"),
            Self::Audio => String::from("AUDIO"),
            Self::Other => String::from("OTHER"),
        }
    }
}

impl Default for AssetTypeEnum {
    fn default() -> AssetTypeEnum {
        Self::Image
    }
}




