/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetCountByUserIdResponseDto {
    #[serde(rename = "photos")]
    pub photos: i32,
    #[serde(rename = "videos")]
    pub videos: i32,
}

impl AssetCountByUserIdResponseDto {
    pub fn new(photos: i32, videos: i32) -> AssetCountByUserIdResponseDto {
        AssetCountByUserIdResponseDto {
            photos,
            videos,
        }
    }
}


