/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CheckDuplicateAssetDto {
    #[serde(rename = "deviceAssetId")]
    pub device_asset_id: String,
    #[serde(rename = "deviceId")]
    pub device_id: String,
}

impl CheckDuplicateAssetDto {
    pub fn new(device_asset_id: String, device_id: String) -> CheckDuplicateAssetDto {
        CheckDuplicateAssetDto {
            device_asset_id,
            device_id,
        }
    }
}


