/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CheckDuplicateAssetResponseDto {
    #[serde(rename = "isExist")]
    pub is_exist: bool,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl CheckDuplicateAssetResponseDto {
    pub fn new(is_exist: bool) -> CheckDuplicateAssetResponseDto {
        CheckDuplicateAssetResponseDto {
            is_exist,
            id: None,
        }
    }
}


