/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAlbumDto {
    #[serde(rename = "albumName")]
    pub album_name: String,
    #[serde(rename = "sharedWithUserIds", skip_serializing_if = "Option::is_none")]
    pub shared_with_user_ids: Option<Vec<String>>,
    #[serde(rename = "assetIds", skip_serializing_if = "Option::is_none")]
    pub asset_ids: Option<Vec<String>>,
}

impl CreateAlbumDto {
    pub fn new(album_name: String) -> CreateAlbumDto {
        CreateAlbumDto {
            album_name,
            shared_with_user_ids: None,
            asset_ids: None,
        }
    }
}


