/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeleteAssetDto {
    #[serde(rename = "ids")]
    pub ids: Vec<String>,
}

impl DeleteAssetDto {
    pub fn new(ids: Vec<String>) -> DeleteAssetDto {
        DeleteAssetDto {
            ids,
        }
    }
}


