/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeleteAssetResponseDto {
    #[serde(rename = "status")]
    pub status: crate::models::DeleteAssetStatus,
    #[serde(rename = "id")]
    pub id: String,
}

impl DeleteAssetResponseDto {
    pub fn new(status: crate::models::DeleteAssetStatus, id: String) -> DeleteAssetResponseDto {
        DeleteAssetResponseDto {
            status,
            id,
        }
    }
}


