/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceTypeEnum {
    #[serde(rename = "IOS")]
    Ios,
    #[serde(rename = "ANDROID")]
    Android,
    #[serde(rename = "WEB")]
    Web,

}

impl ToString for DeviceTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Ios => String::from("IOS"),
            Self::Android => String::from("ANDROID"),
            Self::Web => String::from("WEB"),
        }
    }
}

impl Default for DeviceTypeEnum {
    fn default() -> DeviceTypeEnum {
        Self::Ios
    }
}




