/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeviceInfoResponseDto {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "deviceType")]
    pub device_type: crate::models::DeviceTypeEnum,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "deviceId")]
    pub device_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "isAutoBackup")]
    pub is_auto_backup: bool,
}

impl DeviceInfoResponseDto {
    pub fn new(id: i32, device_type: crate::models::DeviceTypeEnum, user_id: String, device_id: String, created_at: String, is_auto_backup: bool) -> DeviceInfoResponseDto {
        DeviceInfoResponseDto {
            id,
            device_type,
            user_id,
            device_id,
            created_at,
            is_auto_backup,
        }
    }
}


