/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ExifResponseDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "fileSizeInByte", skip_serializing_if = "Option::is_none")]
    pub file_size_in_byte: Option<i64>,
    #[serde(rename = "make", skip_serializing_if = "Option::is_none")]
    pub make: Option<String>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(rename = "imageName", skip_serializing_if = "Option::is_none")]
    pub image_name: Option<String>,
    #[serde(rename = "exifImageWidth", skip_serializing_if = "Option::is_none")]
    pub exif_image_width: Option<f32>,
    #[serde(rename = "exifImageHeight", skip_serializing_if = "Option::is_none")]
    pub exif_image_height: Option<f32>,
    #[serde(rename = "orientation", skip_serializing_if = "Option::is_none")]
    pub orientation: Option<String>,
    #[serde(rename = "dateTimeOriginal", skip_serializing_if = "Option::is_none")]
    pub date_time_original: Option<String>,
    #[serde(rename = "modifyDate", skip_serializing_if = "Option::is_none")]
    pub modify_date: Option<String>,
    #[serde(rename = "lensModel", skip_serializing_if = "Option::is_none")]
    pub lens_model: Option<String>,
    #[serde(rename = "fNumber", skip_serializing_if = "Option::is_none")]
    pub f_number: Option<f32>,
    #[serde(rename = "focalLength", skip_serializing_if = "Option::is_none")]
    pub focal_length: Option<f32>,
    #[serde(rename = "iso", skip_serializing_if = "Option::is_none")]
    pub iso: Option<f32>,
    #[serde(rename = "exposureTime", skip_serializing_if = "Option::is_none")]
    pub exposure_time: Option<f32>,
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f32>,
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f32>,
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

impl ExifResponseDto {
    pub fn new() -> ExifResponseDto {
        ExifResponseDto {
            id: None,
            file_size_in_byte: None,
            make: None,
            model: None,
            image_name: None,
            exif_image_width: None,
            exif_image_height: None,
            orientation: None,
            date_time_original: None,
            modify_date: None,
            lens_model: None,
            f_number: None,
            focal_length: None,
            iso: None,
            exposure_time: None,
            latitude: None,
            longitude: None,
            city: None,
            state: None,
            country: None,
        }
    }
}


