/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAssetByTimeBucketDto {
    #[serde(rename = "timeBucket")]
    pub time_bucket: Vec<String>,
}

impl GetAssetByTimeBucketDto {
    pub fn new(time_bucket: Vec<String>) -> GetAssetByTimeBucketDto {
        GetAssetByTimeBucketDto {
            time_bucket,
        }
    }
}


