/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogoutResponseDto {
    #[serde(rename = "successful")]
    pub successful: bool,
}

impl LogoutResponseDto {
    pub fn new(successful: bool) -> LogoutResponseDto {
        LogoutResponseDto {
            successful,
        }
    }
}


