/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SearchAssetDto {
    #[serde(rename = "searchTerm")]
    pub search_term: String,
}

impl SearchAssetDto {
    pub fn new(search_term: String) -> SearchAssetDto {
        SearchAssetDto {
            search_term,
        }
    }
}


