/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServerInfoResponseDto {
    #[serde(rename = "diskSizeRaw")]
    pub disk_size_raw: i64,
    #[serde(rename = "diskUseRaw")]
    pub disk_use_raw: i64,
    #[serde(rename = "diskAvailableRaw")]
    pub disk_available_raw: i64,
    #[serde(rename = "diskUsagePercentage")]
    pub disk_usage_percentage: f32,
    #[serde(rename = "diskSize")]
    pub disk_size: String,
    #[serde(rename = "diskUse")]
    pub disk_use: String,
    #[serde(rename = "diskAvailable")]
    pub disk_available: String,
}

impl ServerInfoResponseDto {
    pub fn new(disk_size_raw: i64, disk_use_raw: i64, disk_available_raw: i64, disk_usage_percentage: f32, disk_size: String, disk_use: String, disk_available: String) -> ServerInfoResponseDto {
        ServerInfoResponseDto {
            disk_size_raw,
            disk_use_raw,
            disk_available_raw,
            disk_usage_percentage,
            disk_size,
            disk_use,
            disk_available,
        }
    }
}


