/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServerVersionReponseDto {
    #[serde(rename = "major")]
    pub major: i32,
    #[serde(rename = "minor")]
    pub minor: i32,
    #[serde(rename = "patch")]
    pub patch: i32,
    #[serde(rename = "build")]
    pub build: i32,
}

impl ServerVersionReponseDto {
    pub fn new(major: i32, minor: i32, patch: i32, build: i32) -> ServerVersionReponseDto {
        ServerVersionReponseDto {
            major,
            minor,
            patch,
            build,
        }
    }
}


