/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ThumbnailFormat {
    #[serde(rename = "JPEG")]
    Jpeg,
    #[serde(rename = "WEBP")]
    Webp,

}

impl ToString for ThumbnailFormat {
    fn to_string(&self) -> String {
        match self {
            Self::Jpeg => String::from("JPEG"),
            Self::Webp => String::from("WEBP"),
        }
    }
}

impl Default for ThumbnailFormat {
    fn default() -> ThumbnailFormat {
        Self::Jpeg
    }
}




