/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateAlbumDto {
    #[serde(rename = "albumName", skip_serializing_if = "Option::is_none")]
    pub album_name: Option<String>,
    #[serde(rename = "albumThumbnailAssetId", skip_serializing_if = "Option::is_none")]
    pub album_thumbnail_asset_id: Option<String>,
}

impl UpdateAlbumDto {
    pub fn new() -> UpdateAlbumDto {
        UpdateAlbumDto {
            album_name: None,
            album_thumbnail_asset_id: None,
        }
    }
}


