/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateUserDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "isAdmin", skip_serializing_if = "Option::is_none")]
    pub is_admin: Option<bool>,
    #[serde(rename = "shouldChangePassword", skip_serializing_if = "Option::is_none")]
    pub should_change_password: Option<bool>,
    #[serde(rename = "profileImagePath", skip_serializing_if = "Option::is_none")]
    pub profile_image_path: Option<String>,
}

impl UpdateUserDto {
    pub fn new(id: String) -> UpdateUserDto {
        UpdateUserDto {
            id,
            password: None,
            first_name: None,
            last_name: None,
            is_admin: None,
            should_change_password: None,
            profile_image_path: None,
        }
    }
}


