/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserCountResponseDto {
    #[serde(rename = "userCount")]
    pub user_count: i32,
}

impl UserCountResponseDto {
    pub fn new(user_count: i32) -> UserCountResponseDto {
        UserCountResponseDto {
            user_count,
        }
    }
}


